### PR TITLE
Action after final retry 

### PR DESCRIPTION
**Pull request by yftachman**
Responding to a request (+ my own wishes)
https://github.com/michael-wolfenden/Polly/issues/31

Added a syntax to do an action after the final retry has failed

Policy.Handle()
.AfterFinalRetryFailure(ex => AfterFinalRetryLogic(ex))
.Retry(2)
..Execute(() => Logic());

### CODE REVIEW

**Comment by tapmantwo** [comment]
:+1:

**Comment by Caldas** [comment]
:+1:

**Comment by michael-wolfenden** [comment]
@yftachman, thanks for your contribution, but I have tackled this in another way. Version 2.2.3 now includes post execute support that will allow you to do what you are suggesting.

**Comment by tapmantwo** [comment]
Great, thanks :smiley_cat:

**Pull request closed without merging**
